name: 'Build single package with Melange'
description: |
  This action generates a package using Melange. It assumes that
  the Melange repository is already configured.

inputs:
  version:
    description: 'Version of melange to install (tip, latest-release, v0.5.5, etc.)'
    required: true
    default: 'latest-release'
  
  config:
    description: |
      The config file to use for building the package.
    default: .melange.yaml

  multi-config:
    description: |
      Comma-separated list of config files to use for building package(s).
    default: ''

  config-file-license:
    description: |
      License to use for the melange config itself.
    default: Apache-2.0

  archs:
    description: |
      The architectures to use.
    default: x86_64

  sign-with-temporary-key:
    description: |
      Sign packages with a temporary key, useful for multi-stage
      pipelines.
    default: false

  sign-with-key:
    description: |
      Sign packages with a key, useful for multi-stage
      pipelines.
    default: false

  signing-key-path:
    description: |
      The path for the signing key if signing is enabled.
    default: ''

  repository-path:
    description: |
      The path of the repository being constructed by Melange.
    default: ${{ github.workspace }}/packages

  tests-repository-append:
    description: |
      A list of paths or URIs of repositories that should be
      implicitly included in the test environment.
    default: ''

  repository-append:
    description: |
      A list of paths or URIs of repositories that should be
      implicitly included in the build environment.
    default: ''

  tests-keyring-append:
    description: |
      A list of paths or URIs of keys that should be included
      in the test environment.
    default: ''

  keyring-append:
    description: |
      A list of paths or URIs of keys that should be included
      in the build environment.
    default: ''

  workspace-dir:
    description: |
      The directory to use as the workspace.
    default: ''

  namespace:
    description: |
      Namespace string to use in SBOM purls identifying built packages (eg wolfi, alpine)
    default: ''

  empty-workspace:
    description: |
      Whether to use an empty workspace or not.
    default: false

  source-dir:
    description: |
      The source directory to use if empty-workspace is false.
    default: ${{ github.workspace }}

  s3-bucket-name:
    required: true

  cache-dir:
    description: |
      Directory used for cached inputs.
    default: ''

  pipeline-dir:
    description: |
      Directory used for pipelines.
    default: ${{ github.workspace }}/pipelines

  git-commit:
    description: |
      Commit hash of the git repository containing the build config file.
    default: ''

  git-repo-url:
    description: |
      URL of the git repository containing the build config file.
    default: ''

  build-date:
    description: |
      Build date to use for the package.
    default: ''

runs:
  using: 'composite'

  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ "${{ inputs.sign-with-key }}" == "true" && "${{ inputs.sign-with-temporary-key }}" == "true" ]]; then
          echo "Error: Both 'sign-with-key' and 'sign-with-temporary-key' cannot be enabled at the same time."
          exit 1
        fi
        if [[ ("${{ inputs.sign-with-key }}" == "true" || "${{ inputs.sign-with-temporary-key }}" == "true") && -z "${{ inputs.signing-key-path }}" ]]; then
          echo "Error: 'signing-key-path' cannot be empty when 'sign-with-key' or 'sign-with-temporary-key' is enabled."
          exit 1
        fi
        if [[ -z "$AWS_ACCESS_KEY_ID" || -z "$AWS_SECRET_ACCESS_KEY" || -z "$ENDPOINT_URL" ]]; then
          echo "AWS credentials or endpoint not configured"
          exit 1
        fi

    - name: Generate temporary signing key
      if: ${{ inputs.sign-with-temporary-key == 'true' && inputs.signing-key-path != '' }}
      shell: bash
      run: |
        docker run --rm -v "${{ github.workspace }}:${{ github.workspace }}" -w "${{ github.workspace }}" cgr.dev/chainguard/melange keygen "${{ inputs.signing-key-path }}"

    - name: Set signing key from secret
      if: ${{ inputs.sign-with-key == 'true' && inputs.signing-key-path != '' }}
      shell: bash
      run: |
        echo -n "$MELANGE_PRIVATE_KEY" > "${{ inputs.signing-key-path }}"
        chmod 400 "${{ inputs.signing-key-path }}"

    - name: Build packages with melange (container)
      shell: bash
      run: |
        melangeconfigs="${{ inputs.multi-config }}"
        [[ "${melangeconfigs}" != "" ]] || melangeconfigs="${{ inputs.config }}"

        for config in ${melangeconfigs//,/ }; do
          args=()
          args+=(build "$config")
          args+=(--license "${{ inputs.config-file-license }}" --arch "${{ inputs.archs }}" --out-dir "${{ inputs.repository-path }}")

          [ -n "${{ inputs.repository-append }}" ] && args+=(--repository-append "${{ inputs.repository-append }}")
          [ -n "${{ inputs.keyring-append }}" ] && args+=(--keyring-append "${{ inputs.keyring-append }}")
          [ -n "${{ inputs.workspace-dir }}" ] && args+=(--workspace-dir "${{ inputs.workspace-dir }}")
          [ -n "${{ inputs.namespace }}" ] && args+=(--namespace "${{ inputs.namespace }}")
          [ -n "${{ inputs.cache-dir }}" ] && args+=(--cache-dir "${{ inputs.cache-dir }}")
          [ -n "${{ inputs.pipeline-dir }}" ] && args+=(--pipeline-dir "${{ inputs.pipeline-dir }}")
          [ -n "${{ inputs.git-commit }}" ] && args+=(--git-commit "${{ inputs.git-commit }}")
          [ -n "${{ inputs.git-repo-url }}" ] && args+=(--git-repo-url "${{ inputs.git-repo-url }}")
          [ -n "${{ inputs.build-date }}" ] && args+=(--build-date "${{ inputs.build-date }}")

          if [[ "${{ inputs.empty-workspace }}" == "true" ]]; then
            args+=(--empty-workspace)
          else
            args+=(--source-dir "${{ inputs.source-dir }}/$(dirname "$config")")
          fi

          if [[ "${{ inputs.sign-with-key }}" == "true" || "${{ inputs.sign-with-temporary-key }}" == "true" ]]; then
            args+=(--signing-key "${{ inputs.signing-key-path }}")
          fi

          docker run --privileged --rm -v "${{ github.workspace }}:${{ github.workspace }}" -w "${{ github.workspace }}" \
            cgr.dev/chainguard/melange "${args[@]}"
        done

    - name: Test packages and merge index
      shell: bash
      run: |
        melangeconfigs="${{ inputs.multi-config }}"
        [[ "${melangeconfigs}" != "" ]] || melangeconfigs="${{ inputs.config }}"

        for config in ${melangeconfigs//,/ }; do
          args=(test "$config" --arch "${{ inputs.archs }}")

          if [[ -d "${{ inputs.repository-path }}" ]]; then
            args+=(--repository-append "${{ inputs.repository-path }}")
            args+=(--keyring-append "${{ inputs.signing-key-path }}.pub")
          fi

          [ -n "${{ inputs.tests-repository-append }}" ] && args+=(--repository-append "${{ inputs.tests-repository-append }}")
          [ -n "${{ inputs.tests-keyring-append }}" ] && args+=(--keyring-append "${{ inputs.tests-keyring-append }}")
          [ -n "${{ inputs.workspace-dir }}" ] && args+=(--workspace-dir "${{ inputs.workspace-dir }}")
          [ -n "${{ inputs.pipeline-dir }}" ] && args+=(--pipeline-dirs "${{ inputs.pipeline-dir }}")

          if [[ "${{ inputs.empty-workspace }}" == "true" ]]; then
            args+=(--empty-workspace)
          else
            args+=(--source-dir "${{ inputs.source-dir }}/$(dirname "$config")")
          fi

          docker run --privileged --rm -v "${{ github.workspace }}:${{ github.workspace }}" -w "${{ github.workspace }}" \
            cgr.dev/chainguard/melange "${args[@]}"
        done

        apkindex_path="${{ inputs.repository-path }}/${{ inputs.archs }}/APKINDEX.tar.gz"
        if aws s3 ls "s3://${{ inputs.s3-bucket-name }}/${{ inputs.archs }}/APKINDEX.tar.gz" --endpoint-url="$ENDPOINT_URL" > /dev/null 2>&1; then
          aws s3 cp "s3://${{ inputs.s3-bucket-name }}/${{ inputs.archs }}/APKINDEX.tar.gz" "${{ github.workspace }}"/APKINDEX.tar.gz --endpoint-url="$ENDPOINT_URL"
          docker run --rm -v "${{ github.workspace }}:${{ github.workspace }}" -w "${{ github.workspace }}" \
            cgr.dev/chainguard/melange index \
            --signing-key "${{ inputs.signing-key-path }}" \
            --output "$apkindex_path" "${{ inputs.repository-path }}/${{ inputs.archs }}"/*.apk \
            --source "${{ github.workspace }}"/APKINDEX.tar.gz --merge
        else
          docker run --rm -v "${{ github.workspace }}:${{ github.workspace }}" \
            cgr.dev/chainguard/melange index \
            --signing-key "${{ inputs.signing-key-path }}" \
            --output "$apkindex_path" "${{ inputs.repository-path }}/${{ inputs.archs }}"/*.apk
        fi
