name: 'Build single package with Melange'
description: |
  This action generates a package using Melange. It assumes that
  the Melange repository is already configured.

inputs:
  config:
    description: |
      The config file to use for building the package.
    default: .melange.yaml

  multi-config:
    description: |
      Comma-separated list of config files to use for building package(s).
    default: ''

  config-file-license:
    description: |
      License to use for the melange config itself.
    default: Apache-2.0

  archs:
    description: |
      The architectures to use.
    default: x86_64

  sign-with-temporary-key:
    description: |
      Sign packages with a temporary key, useful for multi-stage
      pipelines.
    default: false

  sign-with-key:
    description: |
      Sign packages with a key, useful for multi-stage
      pipelines.
    default: false

  signing-key-path:
    description: |
      The path for the signing key if signing is enabled.
    default: ''

  repository-path:
    description: |
      The path of the repository being constructed by Melange.
    default: ${{ github.workspace }}/packages

  tests-repository-append:
    description: |
      A list of paths or URIs of repositories that should be
      implicitly included in the test environment.
    default: ''

  repository-append:
    description: |
      A list of paths or URIs of repositories that should be
      implicitly included in the build environment.
    default: ''

  tests-keyring-append:
    description: |
      A list of paths or URIs of keys that should be included
      in the test environment.
    default: ''

  keyring-append:
    description: |
      A list of paths or URIs of keys that should be included
      in the build environment.
    default: ''

  workspace-dir:
    description: |
      The directory to use as the workspace.
    default: ''

  namespace:
    description: |
      Namespace string to use in SBOM purls identifying built packages (eg wolfi, alpine)
    default: ''

  empty-workspace:
    description: |
      Whether to use an empty workspace or not.
    default: false

  source-dir:
    description: |
      The source directory to use if empty-workspace is false.
    default: ${{ github.workspace }}

  s3-bucket-name:
    required: true

  cache-dir:
    description: |
      Directory used for cached inputs.
    default: ''

  pipeline-dir:
    description: |
      Directory used for pipelines.
    default: ${{ github.workspace }}/pipelines

  git-commit:
    description: |
      Commit hash of the git repository containing the build config file.
    default: ''

  git-repo-url:
    description: |
      URL of the git repository containing the build config file.
    default: ''

  build-date:
    description: |
      Build date to use for the package.
    default: ''

runs:
  using: 'composite'

  steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install Melange
      shell: bash
      run: |
        brew install melange

    - name: Validate inputs
      shell: bash
      run: |
        if [[ "${{ inputs.sign-with-key }}" == "true" && "${{ inputs.sign-with-temporary-key }}" == "true" ]]; then
          echo "Error: Both 'sign-with-key' and 'sign-with-temporary-key' cannot be enabled at the same time."
          exit 1
        fi

        if [[ ("${{ inputs.sign-with-key }}" == "true" || "${{ inputs.sign-with-temporary-key }}" == "true") && -z "${{ inputs.signing-key-path }}" ]]; then
          echo "Error: 'signing-key-path' cannot be empty when 'sign-with-key' or 'sign-with-temporary-key' is enabled."
          exit 1
        fi

        if [[ -z "$AWS_ACCESS_KEY_ID" ]]; then
          echo "Error: AWS_ACCESS_KEY_ID is not set."
          exit 1
        fi

        if [[ -z "$AWS_SECRET_ACCESS_KEY" ]]; then
          echo "Error: AWS_SECRET_ACCESS_KEY is not set."
          exit 1
        fi

        if [[ -z "$ENDPOINT_URL" ]]; then
          echo "Error: ENDPOINT_URL is not set."
          exit 1
        fi
    
    - name: Generate temporary signing key
      if: ${{ inputs.sign-with-temporary-key == 'true' && inputs.signing-key-path != '' }}
      shell: bash
      run: |
        melange keygen "${{ inputs.signing-key-path }}"

    - name: Set signing key
      if: ${{ inputs.sign-with-key == 'true' && inputs.signing-key-path != '' }}
      shell: bash
      run: |
        set +x
        echo -n "$MELANGE_PRIVATE_KEY" > "${{ inputs.signing-key-path }}"
        chmod 400 "${{ inputs.signing-key-path }}"
        set -x

    - name: 'Build packages'
      shell: bash
      run: |
        [ -n "${{ inputs.repository-append }}" ] && repoarg="--repository-append ${{ inputs.repository-append }}"
        [ -n "${{ inputs.keyring-append }}" ] && keyringarg="--keyring-append ${{ inputs.keyring-append }}"
        [ -n "${{ inputs.workspace-dir }}" ] && workspacearg="--workspace-dir ${{ inputs.workspace-dir }}"
        [ -n "${{ inputs.namespace }}" ] && nsarg="--namespace ${{ inputs.namespace }}"
        [ -n "${{ inputs.cache-dir }}" ] && cachearg="--cache-dir=${{ inputs.cache-dir }}"
        [ -n "${{ inputs.pipeline-dir }}" ] && pipelinedirarg="--pipeline-dir=${{ inputs.pipeline-dir }}"
        [ -n "${{ inputs.git-commit }}" ] && gitcommitarg="--git-commit ${{ inputs.git-commit }}"
        [ -n "${{ inputs.git-repo-url }}" ] && gitrepoarg="--git-repo-url ${{ inputs.git-repo-url }}"
        [ -n "${{ inputs.build-date }}" ] && builddatearg="--build-date=${{ inputs.build-date }}"
        ${{ inputs.empty-workspace }} && workspacearg="$workspacearg --empty-workspace"
        ${{ inputs.empty-workspace }} || workspacearg="$workspacearg --source-dir ${{ inputs.source-dir }}/$(basename $(dirname "${{ inputs.source-dir }}"))" && cd "${{ inputs.source-dir }}/$(basename $(dirname "${{ inputs.source-dir }}"))"
        ${{ inputs.sign-with-key || inputs.sign-with-temporary-key }} && signarg="--signing-key ${{ inputs.signing-key-path }}"
        melangeconfigs="${{ inputs.multi-config }}"
        [[ "${melangeconfigs}" != "" ]] || melangeconfigs="${{ inputs.config }}"
        for config in ${melangeconfigs//,/ }; do
          if [[ -d "${{ inputs.repository-path }}" ]]; then
            repoarg="${repoarg} --repository-append ${{ inputs.repository-path }}"
            keyringarg="${keyringarg} --keyring-append ${{ inputs.signing-key-path }}.pub"
          fi
          melange build "$config" --runner docker --license "${{ inputs.config-file-license }}" --arch "${{ inputs.archs }}" --out-dir "${{ inputs.repository-path }}" $signarg $repoarg $keyringarg $workspacearg $nsarg $cachearg $pipelinedirarg $gitcommitarg $gitrepoarg $builddatearg
        done
        if aws s3 ls "s3://${{ inputs.s3-bucket-name }}/${{ inputs.archs }}/APKINDEX.tar.gz" --endpoint-url="$ENDPOINT_URL" > /dev/null 2>&1; then
          echo "APKINDEX.tar.gz found in S3 bucket. Downloading index and merging."
          aws s3 cp "s3://${{ inputs.s3-bucket-name }}/${{ inputs.archs }}/APKINDEX.tar.gz" /tmp/APKINDEX.tar.gz --endpoint-url="$ENDPOINT_URL"
          melange index $signarg --output "${{ inputs.repository-path }}/${{ inputs.archs }}/APKINDEX.tar.gz" "${{ inputs.repository-path }}/${{ inputs.archs }}"/*.apk --source /tmp/APKINDEX.tar.gz --merge
        else
          echo "APKINDEX.tar.gz not found in S3 bucket. Creating a new index."
          melange index $signarg --output "${{ inputs.repository-path }}/${{ inputs.archs }}/APKINDEX.tar.gz" "${{ inputs.repository-path }}/${{ inputs.archs }}"/*.apk
        fi

    - name: 'Fix local repository permissions'
      shell: bash
      run: |
        sudo chown -R runner:runner "${{ inputs.repository-path }}"

    - name: 'Test packages'
      shell: bash
      run: |
        [ -n "${{ inputs.workdir }}" ] && cd "${{ inputs.workdir }}"
        [ -n "${{ inputs.tests-repository-append }}" ] && repoarg="--repository-append ${{ inputs.tests-repository-append }}"
        [ -n "${{ inputs.tests-keyring-append }}" ] && keyringarg="--keyring-append ${{ inputs.tests-keyring-append }}"
        [ -n "${{ inputs.workspace-dir }}" ] && workspacearg="--workspace-dir ${{ inputs.workspace-dir }}"
        [ -n "${{ inputs.cache-dir }}" ] && cachearg="--cache-dir=${{ inputs.cache-dir }}"
        [ -n "${{ inputs.pipeline-dir }}" ] && pipelinedirarg="--pipeline-dirs=${{ inputs.pipeline-dir }}"
        ${{ inputs.empty-workspace }} && workspacearg="$workspacearg --empty-workspace"
        ${{ inputs.empty-workspace }} || workspacearg="$workspacearg --source-dir ${{ inputs.source-dir }}/$(basename $(dirname "${{ inputs.source-dir }}"))" && cd "${{ inputs.source-dir }}/$(basename $(dirname "${{ inputs.source-dir }}"))"
        melangeconfigs="${{ inputs.multi-config }}"
        [[ "${melangeconfigs}" != "" ]] || melangeconfigs="${{ inputs.config }}"
        for config in ${melangeconfigs//,/ }; do
          if [[ -d "${{ inputs.repository-path }}" ]]; then
            repoarg="${repoarg} --repository-append ${{ inputs.repository-path }}"
            keyringarg="${keyringarg} --keyring-append ${{ inputs.signing-key-path }}.pub"
          fi
          melange test "$config" --runner docker --arch "${{ inputs.archs }}" $workspacearg $pipelinedirarg $repoarg $keyringarg
        done

    - name: 'Copy packages to s3 bucket'
      shell: bash
      run: |
        aws s3 cp --recursive "${{ inputs.repository-path }}/" "s3://${{ inputs.s3-bucket-name }}/" --endpoint-url "$ENDPOINT_URL" --checksum-algorithm CRC32
