name: 'Build and publish image with apko'
description: |
  Publish a built image from a YAML configuration file.

inputs:
  apko-image:
    description: |
      The full reference of the wolfi SDK container image to invoke, 
      including registry, repository, and tag or digest.
      Example: ghcr.io/wolfi-dev/sdk:latest
    default: ''

  config:
    description: |
      The config file to use for building the image.
    default: .apko.yaml

  lockfile:
    description: |
      A path to .lock.json file (e.g. produced by apko lock) that constraints versions of packages to the listed ones (default '' means no additional constraints).
    required: false
    default: ''

  tag:
    description: |
      The tag to use for publishing the image.
    required: true

  repository_owner:
    description: |
      The repository owner's GitHub username.
    default: ${{ github.repository_owner }}

  repository:
    description: |
      The repository name.
    default: ${{ github.repository }}

  token:
    description: |
      The repository owner's GitHub token.
    default: ${{ github.token }}

  image_refs:
    description: |
      Path to file where a list of the published image references will be written.
    default: /tmp/apko.images

  keyring-append:
    description: "Local path or URL to extra keys to be included in the keyring"
    required: false
    default: ''

  build-repository-append:
    description: "Local path or URL of extra repositories to be included in the build enviroment"
    required: false
    default: ''

  repository-append:
    description: "Local path or URL of extra repositories to be included in the generated image"
    required: false
    default: ''

  package-append:
    description: "Extra packages to include."
    required: false
    default: ''

  archs:
    description: "Architectures to build for (e.g., x86_64,ppc64le,arm64) -- default is all, unless specified in config."
    required: false
    default: ''

  build-options:
    description: |
      Build options to enable (comma-separated).
    default: ''

  build-date:
    description: "Date used for the timestamps of the files inside the image"
    required: false
    default: ''

  vcs-url:
    description: |
      Detect and embed VCS URLs (default true).
    type: boolean
    required: false
    default: true

  debug:
    description: |
      Enable debug logging (default false).
    type: boolean
    required: false
    default: false

  automount-src:
    description: |
      If this directory is found, create a copy at automount-dest (inside container)
    default: ${{ github.workspace }}/.apko-automount

  automount-dest:
    description: |
      If automount-src is found, create a copy at this location (inside container)
    default: /work

  generic-user:
    description: |
      Username to login to registry.
    required: false
    default: ''

  generic-pass:
    description: |
      Password to login to registry.
    required: false
    default: ''

  annotations:
    description: "OCI annotations to add. Separate with colon (key:value)"
    required: false
    default: ''

  sbom-path:
    description: |
      Path to write the SBOMs.
    required: false
    default: ''

outputs:
  digest:
    value: ${{ steps.docker-run.outputs.digest }}
    description: |
      The digest of the published container image.

runs:
  using: composite
  steps:
  - id: docker-run
    shell: bash
    run: |
      APKO_IMAGE="${{ inputs.apko-image }}"
      if [[ "${APKO_IMAGE}" == "" ]]; then
        echo "Warning: using latest wolfi-dev/sdk image since apko-image input was empty string."
        APKO_IMAGE="ghcr.io/wolfi-dev/sdk:latest"
      fi
      docker run -i --rm --entrypoint /bin/sh \
        --network host \
        -v $PWD:${{ github.workspace }} \
        -v /tmp:/tmp \
        --workdir ${{ github.workspace }} \
        -e "GITHUB_ACTOR=${{ inputs.repository_owner }}" \
        -e "GITHUB_TOKEN=${{ inputs.token }}" \
        -e "REPOSITORY=${{ inputs.repository }}" \
        "${APKO_IMAGE}" \
        -c "$(cat <<"EOF"
      set -o errexit
      set -o pipefail

      if [[ "${{ inputs.generic-user }}" != "" && "${{ inputs.generic-pass }}" != "" ]]; then
        echo "${{ inputs.generic-pass }}" | \
          /usr/bin/apko login -u "${{ inputs.generic-user }}" \
            --password-stdin "$(echo "${{ inputs.tag }}" | cut -d'/' -f1)"
      fi

      if [ -d "${{ inputs.automount-src }}" ]; then
        echo "Creating copy of ${{ inputs.automount-src }} at ${{ inputs.automount-dest }}"
        cp -r "${{ inputs.automount-src }}" "${{ inputs.automount-dest }}"
      fi
      [ -n "${{ inputs.build-date }}" ] && export SOURCE_DATE_EPOCH='${{ inputs.build-date }}'
      [ -n "${{ inputs.keyring-append }}" ] && keys="-k ${{ inputs.keyring-append }}"
      [ -n "${{ inputs.build-repository-append }}" ] && build_repos="-b ${{ inputs.build-repository-append }}"
      [ -n "${{ inputs.repository-append }}" ] && repos="-r ${{ inputs.repository-append }}"
      [ -n "${{ inputs.package-append }}" ] && packages="-p ${{ inputs.package-append }}"
      [ -n  "${{ inputs.archs }}" ] && archs="--arch ${{ inputs.archs }}"
      [ -n  "${{ inputs.annotations }}" ] && annotations="--annotations ${{ inputs.annotations }}"
      build_options=""
      if [ -n "${{ inputs.build-options }}" ]; then
        opts="${{ inputs.build-options }}"
        for opt in ${opts//,/ }; do
          build_options="${build_options} --build-option ${opt}"
        done
      fi

      sbomPath="--sbom-path=${{ inputs.sbom-path }}"
      
      export DIGEST_FILE="/tmp/digest"
      /usr/bin/apko publish \
        --vcs=${{ inputs.vcs-url }} \
        --lockfile=${{ inputs.lockfile }} \
        ${{ inputs.debug && '--log-level debug' }} \
        --image-refs="${{ inputs.image_refs }}" ${{ inputs.config }} ${{ inputs.tag }} $keys $build_repos $repos $packages $archs $annotations $build_options $sbomPath | tee ${DIGEST_FILE}
      echo EXIT CODE: $?
      EOF
      )"

      echo "digest=$(cat /tmp/digest)" >> $GITHUB_OUTPUT
